### ISSUE TITLE
9.0 Full results not visible in Search Results

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1362]
Full results aren't visible in search results
The last few results are hidden beside other components (maybe footer)

**Steps to replicate**
Search 'qbAn' and number of results is written as 17 but if you count all of them, only 15 are visible

Happens when number of results are more than or equal to 5.

**Comment by MySmilingTurban** [comment]
Waheguru jio,
Just a pinch of this one is left.
The last item of scroll views of search results and verses pane is partially visible.

**Comment by inderpreetsingh** [comment]
> Waheguru jio, Just a pinch of this one is left. The last item of scroll views of search results and verses pane is partially visible.

Veerji, can you share the screenshot here?

**Comment by MySmilingTurban** [comment]
![image](https://user-images.githubusercontent.com/51584037/140793825-c2d36f1a-811f-4104-848e-c72bfa05c40c.png)

**Comment by MySmilingTurban** [comment]
Still only half part is visible of last element in the three scrollable panes (shown in pic)
Also, in the display window in presentation mode, there is white spacing appearing now

![image](https://user-images.githubusercontent.com/51584037/142693207-f841b375-d484-4ea7-8e19-a0e20b49d9aa.png)

**Comment by inderpreetsingh** [comment]
Just a little more fine tuning, we can do this if this doesn't include any major change in code.

If the tools are opened at bottom of history, it still hides the last verse of history. You would need to subtract 180px from height if its opened, else 80px, if that's something we can do, go ahead, otherwise I think this works well. 

![Screenshot from 2021-12-01 01-28-41](https://user-images.githubusercontent.com/1131610/144119194-8ce13ede-9e0a-402f-b386-22b8a3ac7673.png)

**Comment by Gauravjeetsingh** [comment]
Fixed in dev, closing this out
