### ISSUE TITLE
Custom background image upload

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/sttm-desktop#188]
allow upload of custom backgrounds (a gallery picker)
for selecting backgrounds, look at gallery pickers such as wordpress add image/media dialogue.

**Comment by inderpreetsingh** [comment]
@prebhdevsingh This idea was discarded in earlier discussions. We had that functionality (in some form) in initial versions of theme editor (now theme picker). However I believe if we do it the following way, we can allow users to upload their background image without hurting the readability or design.
1) Allow users to pick an image but also give them an option of choosing from bunch of negative space images (Sarovar, Sky with Nishan Sahib in one corner, blurred diwali candles). 
2) Add a translucent color overlay above the image (depending upon theme) so that text readability is never hurt

**Comment by inderpreetsingh** [comment]
This was in progress in one of my local branches since long. So finalized it and made a PR #362 

I need to have a conversation with @saintsoldierx veerji regarding some typography and design things before I make it final.
