### ISSUE TITLE
Authentic English Translation

### ISSUE THREAD

**Issue by Sukhdeep2006** [KhalisFoundation/sttm-desktop#2]
Waheguru Ji Ka Khalsa
Waheguru Ji Ki Fateh!!

Veer Ji, I just come across the new version of STTM app and i found it even better than the previous versions. We have been using STTM 2.0 in gurdwara sahib for displaying the translations for the sangat. You are doing a great job. I also wanted to let you know that i have been looking for the line by line english translations over the web and i always come across one file which says translation by "Singh Sahib Sant Singh Khalsa". And when i refer to the first line, as I mentioned below, i tend to get confused  with the english translation as this doesn't match with the punjabi translations available. Same is visible over the STTM app and website. The English and Punjabi translation does not match for this line. Can you please have this English translation verified and corrected, please.  I feel concerned because when the translation of the very first line doesn't seem right it creates a confusion in the mind over the authenticity of the translation in publication.

I apologise if any of my words were wrong or hurting in any sense. You are doing a great job and we as sangat appreciate the sewa you are doing to the humanity.

-------------------------------------------------------

**ਸੋਚੈ** ਸੋਚਿ ਨ ਹੋਵਈ ਜੇ ਸੋਚੀ ਲਖ ਵਾਰ ॥
ਜੇ ਮੈਂ ਲੱਖ ਵਾਰੀ (ਭੀ) (ਇਸ਼ਨਾਨ ਆਦਿਕ ਨਾਲ ਸਰੀਰ ਦੀ) **ਸੁੱਚ ਰੱਖਾਂ**, (ਤਾਂ ਭੀ ਇਸ ਤਰ੍ਹਾਂ) ਸੁੱਚ ਰੱਖਣ ਨਾਲ (ਮਨ ਦੀ) ਸੁੱਚ ਨਹੀਂ ਰਹਿ ਸਕਦੀ ।
**By thinking**, He cannot be reduced to thought, even by thinking hundreds of thousands of times.

--------------------------------------------------------

**Comment by bhajneet** [comment]
Please re-submit what you believe to be the correct translation. Here is another example by Bhai Manmohan Singh:

"By pondering on God, man cannot have a conception of Him, even though he may ponder over lacs of times."

Some believe it should instead be "By washing/cleaning", is that what you're trying to fix? Whatever you think is correct, please let us know, and then we can have a dialogue.

**Comment by Sukhdeep2006** [comment]
Ritual purification, though million-fold, may not purify the mind.
Source: Unconfirmed, but matches with Punjabi translation by Bhai Sahib Singh.
	
By thinking, He cannot be reduced to thought, even by thinking hundreds of
thousands of times.
Source :Singh Sahib Sant Singh Khalsa, MD


Simply by contemplating on God, we cannot understand Him, even though we
may think hundreds of thousands of times.
Source : Dr. Kulwant Singh Khokhar

**Comment by bhajneet** [comment]
Thank you.

The first one by Bhai Sahib Singh seems to be different from the other three. It looks like we're deciding between:

> Thoughtfully one cannot understand, even after hundreds of thousands of thoughts.

> Ritual purification does not purify the mind, even if performed hundreds of thousands of times.

I've always thought the second one is more correct, but the two translations have to do with differing concepts, thinking in the mind vs washing the body and mind. Not sure how to come to a consensus here.

**Comment by bhajneet** [comment]
I also don't know where the source is for the punjabi to english translation that is matching Bhai Sahib Singh, but here is an audio file of [Bhai Joginder Singh Talwara (Daar Ji)](http://www.sikhsoul.com/golden_khajana_files/mp3/Katha/Bhai%20Joginder%20Singh%20Talwara%20-%20Japji%20Sahib%20Veechar/Japji%20Sahib%20Veechar%2003.mp3), explaining the line. Perhaps this can help.

**Comment by Sukhdeep2006** [comment]
I always feel the translation from Bhai Sahib Singh Ji is the most authentic one and the same is reflected in punjabi in STTM too. So anything which goes inline with this seems more accurate to me.

My second source is Sant Singh ji Maskeen, and he explains the same thing.

http://www.gurmatveechar.com/audios/Katha/02_Present_Day_Katha/Giani_Sant_Singh_Maskeen/Jap_Ji_Sahib_Katha/Giani.Sant.Singh.Maskeen--Jap.Ji.Sahib.Katha.01.mp3

Guru ji talk about the ritual bathing in the first line and about the mind/thoughts in the fourth line of this pauri.

ਸੋਚੈ ਸੋਚਿ ਨ ਹੋਵਈ ਜੇ ਸੋਚੀ ਲਖ ਵਾਰ ॥
ਚੁਪੈ ਚੁਪ ਨ ਹੋਵਈ ਜੇ ਲਾਇ ਰਹਾ ਲਿਵ ਤਾਰ ॥
ਭੁਖਿਆ ਭੁਖ ਨ ਉਤਰੀ ਜੇ ਬੰਨਾ ਪੁਰੀਆ ਭਾਰ ॥
**ਸਹਸ ਸਿਆਣਪਾ** ਲਖ ਹੋਹਿ ਤ ਇਕ ਨ ਚਲੈ ਨਾਲਿ ॥

-------------

ਜੇ ਮੈਂ ਲੱਖ ਵਾਰੀ (ਭੀ) (ਇਸ਼ਨਾਨ ਆਦਿਕ ਨਾਲ ਸਰੀਰ ਦੀ) ਸੁੱਚ ਰੱਖਾਂ, (ਤਾਂ ਭੀ ਇਸ ਤਰ੍ਹਾਂ) ਸੁੱਚ ਰੱਖਣ ਨਾਲ (ਮਨ ਦੀ) ਸੁੱਚ ਨਹੀਂ ਰਹਿ ਸਕਦੀ।

Ritual purification does not purify the mind, even if performed hundreds of thousands of times.

**Comment by saintsoldierx** [comment]
Bhai Jagraj Singh (Basics of Sikhi) also done a lot of research into this
and he also states that “soch” is from the word “sucham”. Some also say
it’s a rhetorical device but the meaning of sucham makes more sense in the
context of what Guru Sahib was trying to say the yogis. I could also ask
Bhai Pinderpal Singh tonight if you wish to get more clarification.


On May 10, 2017 at 10:41:38, Sukhdeep2006 (notifications@github.com) wrote:

I always feel the translation from Bhai Sahib Singh Ji is the most
authentic one and the same is reflected in punjabi in STTM too. So anything
which goes inline with this seems more accurate to me.

My second source is Sant Singh ji Maskeen, and he explains the same thing.

http://www.gurmatveechar.com/audios/Katha/02_Present_Day_Katha/Giani_Sant_Singh_Maskeen/Jap_Ji_Sahib_Katha/Giani.Sant.Singh.Maskeen--Jap.Ji.Sahib.Katha.01.mp3

Guru ji talk about the ritual bathing in the first line and about the
mind/thoughts in the fourth line of this pauri.

ਸੋਚੈ ਸੋਚਿ ਨ ਹੋਵਈ ਜੇ ਸੋਚੀ ਲਖ ਵਾਰ ॥
ਚੁਪੈ ਚੁਪ ਨ ਹੋਵਈ ਜੇ ਲਾਇ ਰਹਾ ਲਿਵ ਤਾਰ ॥
ਭੁਖਿਆ ਭੁਖ ਨ ਉਤਰੀ ਜੇ ਬੰਨਾ ਪੁਰੀਆ ਭਾਰ ॥
*ਸਹਸ ਸਿਆਣਪਾ* ਲਖ ਹੋਹਿ ਤ ਇਕ ਨ ਚਲੈ ਨਾਲਿ ॥
------------------------------

ਜੇ ਮੈਂ ਲੱਖ ਵਾਰੀ (ਭੀ) (ਇਸ਼ਨਾਨ ਆਦਿਕ ਨਾਲ ਸਰੀਰ ਦੀ) ਸੁੱਚ ਰੱਖਾਂ, (ਤਾਂ ਭੀ ਇਸ
ਤਰ੍ਹਾਂ) ਸੁੱਚ ਰੱਖਣ ਨਾਲ (ਮਨ ਦੀ) ਸੁੱਚ ਨਹੀਂ ਰਹਿ ਸਕਦੀ।

Ritual purification does not purify the mind, even if performed hundreds of
thousands of times.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KhalisFoundation/sttm-desktop/issues/2#issuecomment-300559150>,
or mute the thread

**Comment by Sukhdeep2006** [comment]
I think we are in agreement here...the word Sochai is NOT for thinking in the first line, but it is for ritual bathing or the outer hygiene or Sucham.

**Comment by Sukhdeep2006** [comment]
![sochai](https://cloud.githubusercontent.com/assets/28600533/25913750/e090a3c0-3589-11e7-9ece-7dacbe375745.jpg)

**Comment by Sarabveer** [comment]
http://gurmatbibek.com/forum/read.php?3,35628

I believe the English Translation is fine here.

**Comment by tarunsingh5** [comment]
@Sukhdeep2006 please sign up to submit changes to translations by following these steps:

https://khalisfoundation.org/wp-content/uploads/2018/01/ShabadOS-Editor-Sign-Up-Instructions.pdf

will close this bug for now
