### ISSUE TITLE
Add Custom Slides Menu

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#56]

**Comment by inderpreetsingh** [comment]
![image](https://user-images.githubusercontent.com/1131610/35918566-4762bbda-0c38-11e8-8d35-3a7a7670b523.png)
Quick wireframe by tarun veerji.

So as per recent discussion with tarun veerji, we will have an add custom slide menu button on right hand side of current shabad container. Custom Slide will contain following items for now
* Add empty Slide (`sendText` with empty string as argument)
* Add waheguru Slide (`sendText` with "waheguru" as argument)
* Add announcement Slide (`sendText`)
Optional (Still to discuss)
* Maybe rename `sendText` to `customSlide`?
* Have a `presetSlides.json` with list of preset slides (waheguru, dhan guru nanak, satnam sri waheguru), so that adding/removing preset slides is easy.

**Comment by inderpreetsingh** [comment]
https://fontawesome.com/icons/clone?style=regular nearest font awesome icon that I could find.

**Comment by tarunsingh5** [comment]
Icon looks good to me just.
